### ISSUE TITLE
vv 2.0 - Roadmap, features, etc

### ISSUE THREAD

**Issue by bradp** [bradp/vv#161]
vv 1.9.0 is complete and waiting to be released. Although this [does not mean that 2.0 needs to be next](http://semver.org/), I believe we're at a good point to release a large update that would necessitate a major version number change.

Here are some things I'd like to tackle for 2.0.

 * [ ] Re-evaluate the questions asked in the wizard. Should they be different, rephrased, more of them, less of them?
 * [ ] [Add a way to save default options from the wizard and all flags](https://github.com/bradp/vv/issues/120)
 * [ ] [Shortcut the re-provisioning process](https://github.com/bradp/vv/issues/146)
 * [ ] Add a way to easily add multisite sub-domains to config.
 * [ ] [Add more checking around ~/.vv-config, check if its writable/etc](https://github.com/bradp/vv/issues/153)
 * [ ] [Fully support HGV](https://github.com/bradp/vv/issues/84)
 * [ ] Re-evaluate blueprints and the implementation to look for improvements.

Anyone have any other ideas / thoughts on features / fixes from a major version update?

**Comment by JasonTheAdams** [comment]
That is awesome. Love the roadmap! Excited to have HGV support!

**Comment by bradp** [comment]
@jtsternberg made a good point about about defaults

**Comment by bradp** [comment]
@jtsternberg made a good point about about defaults. look at apigen, build a way to pass in a file with a list defaults, maybe have a flag for what to prompt the user for.

also thinking about having named defaults, so could do a similar thing, but pass in the name of a set of defaults if you wanted

**Comment by jtsternberg** [comment]
Would love to be able to pass a --config=/path/to/config which would be a file of all my ---flags set instead of calling them via the command line. APIGen would be good prior art.

**Comment by maxfenton** [comment]
Thanks for all of this. VV is *super* helpful to me every day.

**Comment by XedinUnknown** [comment]
Hi,

Looks like you have a lot of issues lined up for the next version, and that is awesome. Just wanted to leave a reminder that the next version after `1.9` is `1.10`, unless the API changes significantly.

Thanks for your amazing work!

**Comment by bradp** [comment]
I am familiar with semantic versioning, and there is a note about that at the top of this issue.

**Comment by XedinUnknown** [comment]
Yes, sir. Just in case, no offence meant :)

**Comment by artifactdev** [comment]
I would love a way to get wp-content from local file system (where it's copied during the installation) and a possibility to get wp-content from a sftp location

**Comment by voltronik** [comment]
It would be great to see automated SSL certificates as an option when creating sites in vv too.

**Comment by sc0ttkclark** [comment]
I also agree that automating the SSL certs would be a great addition as that is constantly a fun part to deal with.
